[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.1.3"
chumsky = "0.5.0"
utils = { path = "../utils" }

[dev-dependencies]
insta = "1.8.0"
